- name: Opened on user's repositories
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.plugin.followup.svg
    token: ${{ secrets.METRICS_TOKEN }}
    base: ""
    plugin_followup: yes

- name: Opened by user
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.plugin.followup.user.svg
    token: ${{ secrets.METRICS_TOKEN }}
    base: ""
    plugin_followup: yes
    plugin_followup_sections: user

- name: Indepth analysis
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.plugin.followup.indepth.svg
    token: ${{ secrets.METRICS_TOKEN }}
    base: ""
    plugin_followup: yes
    plugin_followup_indepth: yes

- name: Exclude Archived
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.plugin.followup.archived.svg
    token: ${{ secrets.METRICS_TOKEN }}
    base: ""
    plugin_followup: yes
    plugin_followup_archived: no
  prod:
    skip: true
